language: java
jdk: oraclejdk8
install: true
cache:
  directories:
  - $HOME/.m2

script:
 - mvn clean install
after_success:
 - bash <(curl -s https://codecov.io/bash)

sudo: false
git:
  depth: false

before_script:
  - _JAVA_OPTIONS=
