language: java
jdk: oraclejdk8
install: true
cache:
  directories:
  - $HOME/.m2

script:
 - mvn clean install

sudo: false
git:
  depth: false

before_script:
  - _JAVA_OPTIONS=

after_success:
  - mvn jacoco:report coveralls:report